apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test
  namespace: argocd
spec:
  description: test project # プロジェクトの説明
  sourceRepos:
    - "*" # 任意のリポジトリを許可
  destinations:
    - namespace: express # デプロイできるnamespace
      server: https://kubernetes.default.svc # デプロイ先のKubernetesクラスタ
    - namespace: postgres # デプロイできるnamespace
      server: https://kubernetes.default.svc # デプロイ先のKubernetesクラスタ
