apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: react
spec:
  selector:
    app: react-app  # Deploymentのラベルに一致させる
  ports:
    - protocol: TCP
      port: 5001       # 外部からアクセスするポートここい
      targetPort: 80  # コンテナがリッスンしているポート
  type: NodePort  # LoadBalancerを使用して外部に公開