apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  namespace: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: ghcr.io/koizumi-yositaka/jwt-react-app:main11417626092
          imagePullPolicy: Always # 常に最新のイメージを取得する
          ports:
            - containerPort: 80
