apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: react
spec:
  selector:
    app: react-app  # Deploymentのラベルに一致させる
  ports:
    - protocol: TCP
      port: 80      # 外部からアクセスするポートここい
      targetPort: 80  # コンテナがリッスンしているポート
      nodePort: 30001
  type: NodePort  # LoadBalancerを使用して外部に公開
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-app-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-app-service
            port:
              number: 80
