apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  namespace: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: ghcr.io/koizumi-yositaka/jwt-react-app:latest
        imagePullPolicy: Always  # 常に最新のイメージを取得
        ports:
        - containerPort: 80
        env: 
          - name: VITE_API_BASE_URL
            value: http://localhost:80/