apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: react
spec:
  selector:
    app: react-app  # Deploymentのラベルに一致させる
  ports:
    - protocol: TCP
      port: 80      # 外部からアクセスするポートここい
      targetPort: 80  # コンテナがリッスンしているポート
      nodePort: 30001
