apiVersion: v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13 # 使用するPostgreSQLのバージョン
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "users"  # データベース名
            - name: POSTGRES_USER
              value: "admin"  # ユーザー名
            - name: POSTGRES_PASSWORD
              value: "test"  # パスワード
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
