apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app  # Deploymentのラベルに一致させる
  ports:
    - protocol: TCP
      port: 5000       # 外部からアクセスするポートここい
      targetPort: 5000  # コンテナがリッスンしているポート
  type: LoadBalancer  # LoadBalancerを使用して外部に公開