apiVersion: v1
kind: ConfigMap
metadata:
  name: express-config
data:
  PORT: "8080"
  DB_NAME: users
  DB_USER: "admin"
  DB_PASS: "test"
  DB_HOST: "postgres-service.postgres.svc.cluster.local"
  JWT_SECRET: "HCujmweMScV3DwZKtrE7RG7sE8bXDjVy"
  ACCESS_TOKEN_DURATION_MINUTE: "2"
  REFRESH_TOKEN_DURATION_MINUTE: "1440"
  REFRESH_TOKEN_NEW_TOKEN: "true"
  REFRESH_TOKEN_RESET_EXP: "false"
  REACT_PORT: "30001"
