apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment
  namespace: express # 名前空間を指定
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: express-app
          image: ghcr.io/koizumi-yositaka/jwt-tutorial:dev11635490356
          imagePullPolicy: Always # 常に最新のイメージを取得
          ports:
            - containerPort: 8081
          env:
            - name: REFRESH_TOKEN_DURATION_MINUTE
              valueFrom:
                configMapKeyRef:
                  name: express-config
                  key: REFRESH_TOKEN_DURATION_MINUTE
            - name: DB_CONN
              valueFrom:
                configMapKeyRef:
                  name: express-config
                  key: DB_CONN
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: express-secret
                  key: JWT_SECRET
            - name: ACCESS_TOKEN_DURATION_MINUTE
              valueFrom:
                configMapKeyRef:
                  name: express-config
                  key: ACCESS_TOKEN_DURATION_MINUTE
            - name: REFRESH_TOKEN_NEW_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: express-config
                  key: REFRESH_TOKEN_NEW_TOKEN
            - name: REFRESH_TOKEN_RESET_EXP
              valueFrom:
                configMapKeyRef:
                  name: express-config
                  key: REFRESH_TOKEN_RESET_EXP
            - name: REACT_PORT
              valueFrom:
                configMapKeyRef:
                  name: express-config
                  key: REACT_PORT
            - name: EXPRESS_PORT
              valueFrom:
                configMapKeyRef:
                  name: express-config
                  key: EXPRESS_PORT
            - name: EXPRESS_PORT
              valueFrom:
                configMapKeyRef:
                  name: express-config
                  key: YAHOO_APP_ID