name: PR Notification to Teams

on:
  pull_request:
    types: [opened, reopened]  # PR 作成や更新時に実行

jobs:
  notify-teams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send PR Notification to Microsoft Teams
        env:
          WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          pr_url="${{ github.event.pull_request.html_url }}"
          pr_author="${{ github.event.pull_request.user.login }}"
          repo_name="${{ github.repository }}"

          curl -H 'Content-Type: application/json' \
               -d '{
                    "title": "新しい Pull Request が作成されました。",
                    "text": "'"$pr_title"' by '"$pr_author"'",
                    "sections": [{
                      "activityTitle": "リポジトリ: '"$repo_name"'",
                      "activitySubtitle": "[PRを確認する]('"$pr_url"')",
                      "markdown": true
                    }]
                  }' \
               $WEBHOOK_URL
