name: PR Notification to Teams

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify-teams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send PR Notification to Microsoft Teams
        env:
          WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          # 必要な情報を取得
          pr_title="${{ github.event.pull_request.title }}"
          pr_url="${{ github.event.pull_request.html_url }}"
          pr_author="${{ github.event.pull_request.user.login }}"
          repo_name="${{ github.repository }}"

          # 空のフィールドをチェック（エラーを防ぐため）
          pr_title=${pr_title:-"No Title"}
          pr_author=${pr_author:-"Unknown Author"}

          # JSON データの組み立て
          payload=$(cat <<-EOF
          {
            "title": "新しい Pull Request が作成されました",
            "text": "タイトル: $pr_title\n作成者: $pr_author",
            "sections": [{
              "activityTitle": "リポジトリ: $repo_name",
              "activitySubtitle": "[PRを確認する]($pr_url)",
              "markdown": true
            }]
          }
          EOF
          )

          # Webhook 送信
          curl -X POST -H 'Content-Type: application/json' \
               -d "$payload" \
               "$WEBHOOK_URL"
